## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [9]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [10]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [12]:
from sklearn.model_selection import train_test_split
y1_index = range(40)       # y是1的索引值(前40個)
y0_index = range(40,200)   # y是0的索引值(40之後到200個)

X1_train, X1_test, y1_train, y1_test = train_test_split(X[y1_index], y[y1_index], test_size=0.25) #X的前40個，和Y的前40個，取四分之一就是10個

X0_train, X0_test, y0_train, y0_test = train_test_split(X[y0_index], y[y0_index], test_size=10) #X的後160的，和Y的後160個，直接取整數10個

In [14]:
print('X0_test:' + str(X0_test))
print('X1_test:' + str(X1_test))
print('y0_test:' + str(y0_test))
print('y1_test:' + str(y1_test))

X0_test:[[290 291 292 293 294]
 [685 686 687 688 689]
 [300 301 302 303 304]
 [200 201 202 203 204]
 [970 971 972 973 974]
 [335 336 337 338 339]
 [210 211 212 213 214]
 [730 731 732 733 734]
 [715 716 717 718 719]
 [925 926 927 928 929]]
X1_test:[[130 131 132 133 134]
 [ 30  31  32  33  34]
 [  0   1   2   3   4]
 [ 35  36  37  38  39]
 [160 161 162 163 164]
 [110 111 112 113 114]
 [ 25  26  27  28  29]
 [135 136 137 138 139]
 [ 65  66  67  68  69]
 [  5   6   7   8   9]]
y0_test:[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
y1_test:[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [15]:
# 把前40和後160的資料合併
X_train= np.append(X0_train, X1_train)
X_test=np.append(X0_test, X1_test)
y_train=np.append(y0_train, y1_train)
y_test=np.append(y0_test, y1_test)

In [17]:
y_test

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])